### ISSUE TITLE
Remove docker.io for good

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/enovm#1]
https://github.com/enowars/enovm/blob/a9322a01812a004aa21964cef7a1215062cae1d4/ansible/roles/docker/tasks/main.yml#L61

I guess we can safely scrap that now? @Liikt

**Comment by ldruschk** [comment]
This was resolved in https://github.com/enowars/enovm/commit/d75391fb8e053c07b1150df0c17345be765574fe#diff-8a4c758b73a215ce668fd13badf3fb17
